var Nightmare = require("nightmare");
require('nightmare-upload')(Nightmare);
var nightmare = Nightmare({ show: true});

nightmare
.goto("http://burbz-mvp-angular-app.s3-website-us-east-1.amazonaws.com/")
.click('.loginBtn')
.wait(1000)
.type("#mat-input-6", "dahill.chay@gmail.com")
.type("#mat-input-7", "Burbz12!")
.click("#signupbutton")
.wait(1000)
.click('[href="/property/list"]')
.wait(1000)
.click('[href="/property/create"]')
.wait(1000)
.type('[formcontrolname="address"]','149 E Main St')
.type('[formcontrolname="city"]','Chandler')
.type('[formcontrolname="state"]','AZ')
.type('[formcontrolname="zip"]','85224')
.click('[formcontrolname="dwelling_type"]')
.wait(300)
.click('[value="townhouse"]')
.type('[formcontrolname="square_footage"]','1000')
.type('[formcontrolname="levels"]','1')
.type('[formcontrolname="bedrooms"]','3')
.type('[formcontrolname="bathrooms"]','2.5')
.type('[formcontrolname="units"]','1')
.type('[formcontrolname="current_rent"]','1000')
.click('[formcontrolname="occupant_status"]')
.wait(300)
.click('[value="Owner"]')
.type('[formcontrolname="security_deposit_amount"]','150')
.click('[formcontrolname="pets"]')
.wait(300)
.click('[value="None"')
.click('[formcontrolname="pool"]')
.wait(300)
.click('[value="Private Only"]')
.click('[formcontrolname="laundry"]')
.wait(300)
.click('[value="included"]')
.click('[formcontrolname="cooling"]')
.wait(300)
.click('[value="evap"]')
.click('[formcontrolname="heating"]')
.wait(300)
.click('[value="Gas Heat"]')
.click('[formcontrolname="parking"]')
.wait(300)
.click('[value="Garage"]')
.type('[formcontrolname="application_fees"]','10')
// .click('button.mat-raised-button')
// .upload('house', '/assets/house.jpg')
// .click('#btnSave')
.wait(2000)
.url()
.then(url => {
  console.log(url);
})
.catch(function(err) {
    console.error("Error: " + err);
});